services:
  database:
    container_name: slv_database
    image: mysql:8.0.39
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        APP_ENV: ${APP_ENV}
        APP_SECRET: ${APP_SECRET}
    ports:
        - "3308:3306"
    volumes:
      - database_data:/var/lib/mysql:rw
  
  app:
    container_name: slv_app
    build: .
    volumes:
        - .:/app:rw,cached
    ports:
        - "8082:80"
        - "4043:443"
    
volumes:
  database_data:
